image: node:9.11.1

pages:
  cache:
    paths:
    - node_modules/

  script:
  - npm install
  - npm install -g vuepress
  - npm run docs:build
  artifacts:
    paths:
    - public
  only:
  - master